server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/purchase_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    druid:
      initialSize: 10
      minIdle: 10
      maxActive: 500
      maxWait: 60000
  jpa:
    show-sql: true
    open-in-view: false
